"""added likes to post

Revision ID: d911f11d740f
Revises: 9fc1bfec1e94
Create Date: 2026-07-06 08:01:27.438054

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d911f11d740f"
down_revision: str | Sequence[str] | None = "9fc1bfec1e94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("likes", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###
